name: Build Windows EXE
on:
  workflow_dispatch: {}
  push:
    tags: ["v*"]   # build when you push a tag like v1.0.0

jobs:
  win-build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]   # or "3.13" if you updated SciPy to >=1.14.1
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt "pyinstaller>=6.6"

      - name: Verify SciPy import
        run: python -c "import scipy,sys;print('SciPy',scipy.__version__,'Python',sys.version.split()[0])"

      - name: Build (spec if present, else CLI)
        shell: bash
        run: |
          if [ -f "SPX_0DTE_Backtester_fixed.spec" ]; then
            pyinstaller SPX_0DTE_Backtester_fixed.spec
          else
            pyinstaller --noconfirm --clean --windowed --onefile \
              --name SPX_0DTE_Backtester \
              --collect-submodules scipy --collect-data scipy \
              --collect-submodules numpy --collect-data numpy \
              --hidden-import=scipy._lib.messagestream \
              --hidden-import=PyQt6 --hidden-import=matplotlib \
              --hidden-import=pandas --hidden-import=aiohttp \
              main.py
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SPX_0DTE_Backtester-${{ matrix.python-version }}
          path: dist/**
          if-no-files-found: error
